"""
Base de données des artistes français connus avec leurs métriques et cachets estimés.
Ces données sont basées sur des informations publiques et des estimations du marché.
"""

from typing import Dict, Any, Optional
from dataclasses import dataclass
import random


@dataclass
class KnownArtistData:
    """Données d'un artiste connu"""
    name: str
    real_name: Optional[str]
    genre: str
    spotify_monthly_listeners: int  # Approximation
    youtube_subscribers: int
    instagram_followers: int
    tiktok_followers: int
    fee_min: int
    fee_max: int
    market_tier: str
    record_label: Optional[str]
    management: Optional[str]
    booking_agency: Optional[str]


# Base de données des artistes français connus
# Données approximatives basées sur des sources publiques (2024-2025)
KNOWN_ARTISTS_DB: Dict[str, KnownArtistData] = {
    # ===== RAP FR - SUPERSTARS =====
    "jul": KnownArtistData(
        name="Jul",
        real_name="Julien Mari",
        genre="RAP",
        spotify_monthly_listeners=12000000,
        youtube_subscribers=8500000,
        instagram_followers=6000000,
        tiktok_followers=3000000,
        fee_min=150000,
        fee_max=300000,
        market_tier="superstar",
        record_label="D'Or et de Platine",
        management="Liga One Industry",
        booking_agency=None,
    ),
    "pnl": KnownArtistData(
        name="PNL",
        real_name="Ademo & N.O.S",
        genre="RAP",
        spotify_monthly_listeners=8000000,
        youtube_subscribers=5000000,
        instagram_followers=4500000,
        tiktok_followers=500000,
        fee_min=200000,
        fee_max=400000,
        market_tier="superstar",
        record_label="QLF Records",
        management="QLF",
        booking_agency=None,
    ),
    "nekfeu": KnownArtistData(
        name="Nekfeu",
        real_name="Ken Samaras",
        genre="RAP",
        spotify_monthly_listeners=7500000,
        youtube_subscribers=3200000,
        instagram_followers=3000000,
        tiktok_followers=400000,
        fee_min=120000,
        fee_max=250000,
        market_tier="superstar",
        record_label="Seine Zoo",
        management="Seine Zoo",
        booking_agency="Auguri Productions",
    ),
    "orelsan": KnownArtistData(
        name="Orelsan",
        real_name="Aurélien Cotentin",
        genre="RAP",
        spotify_monthly_listeners=8500000,
        youtube_subscribers=4000000,
        instagram_followers=3500000,
        tiktok_followers=1500000,
        fee_min=150000,
        fee_max=350000,
        market_tier="superstar",
        record_label="7th Magnitude / Wagram",
        management="7th Magnitude",
        booking_agency="Auguri Productions",
    ),
    "ninho": KnownArtistData(
        name="Ninho",
        real_name="William Nzobazola",
        genre="RAP",
        spotify_monthly_listeners=11000000,
        youtube_subscribers=6000000,
        instagram_followers=5500000,
        tiktok_followers=2000000,
        fee_min=120000,
        fee_max=250000,
        market_tier="superstar",
        record_label="Rec. 118",
        management="Rec. 118",
        booking_agency=None,
    ),
    "booba": KnownArtistData(
        name="Booba",
        real_name="Élie Yaffa",
        genre="RAP",
        spotify_monthly_listeners=6000000,
        youtube_subscribers=5500000,
        instagram_followers=7000000,
        tiktok_followers=1000000,
        fee_min=150000,
        fee_max=350000,
        market_tier="superstar",
        record_label="Tallac Records",
        management="Tallac Records",
        booking_agency=None,
    ),
    "aya nakamura": KnownArtistData(
        name="Aya Nakamura",
        real_name="Aya Danioko",
        genre="POP/RNB",
        spotify_monthly_listeners=25000000,
        youtube_subscribers=8000000,
        instagram_followers=7500000,
        tiktok_followers=5000000,
        fee_min=200000,
        fee_max=500000,
        market_tier="mega_star",
        record_label="Warner Music France",
        management=None,
        booking_agency=None,
    ),
    
    # ===== RAP FR - STARS =====
    "sdm": KnownArtistData(
        name="SDM",
        real_name="Léonard Manzambi",
        genre="RAP",
        spotify_monthly_listeners=5500000,
        youtube_subscribers=1800000,
        instagram_followers=2000000,
        tiktok_followers=800000,
        fee_min=60000,
        fee_max=120000,
        market_tier="star",
        record_label="92i / Rec. 118",
        management="92i",
        booking_agency=None,
    ),
    "gazo": KnownArtistData(
        name="Gazo",
        real_name="Gadji Faré Traoré",
        genre="RAP",
        spotify_monthly_listeners=7000000,
        youtube_subscribers=2500000,
        instagram_followers=3000000,
        tiktok_followers=1500000,
        fee_min=80000,
        fee_max=150000,
        market_tier="star",
        record_label="Piraterie Music",
        management="Piraterie Music",
        booking_agency=None,
    ),
    "tiakola": KnownArtistData(
        name="Tiakola",
        real_name="Christopher Music",
        genre="RAP",
        spotify_monthly_listeners=8000000,
        youtube_subscribers=1500000,
        instagram_followers=2500000,
        tiktok_followers=1200000,
        fee_min=70000,
        fee_max=140000,
        market_tier="star",
        record_label="4Keus Music",
        management="4Keus Music",
        booking_agency=None,
    ),
    "damso": KnownArtistData(
        name="Damso",
        real_name="William Kalubi",
        genre="RAP",
        spotify_monthly_listeners=9000000,
        youtube_subscribers=4000000,
        instagram_followers=4500000,
        tiktok_followers=1000000,
        fee_min=100000,
        fee_max=200000,
        market_tier="superstar",
        record_label="Vie/92i",
        management=None,
        booking_agency=None,
    ),
    "freeze corleone": KnownArtistData(
        name="Freeze Corleone",
        real_name="Issa Lorenzo Diakhaté",
        genre="RAP",
        spotify_monthly_listeners=4500000,
        youtube_subscribers=1200000,
        instagram_followers=1500000,
        tiktok_followers=500000,
        fee_min=60000,
        fee_max=120000,
        market_tier="star",
        record_label="667",
        management="667",
        booking_agency=None,
    ),
    "laylow": KnownArtistData(
        name="Laylow",
        real_name="Rachid Music",
        genre="RAP",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=800000,
        instagram_followers=900000,
        tiktok_followers=300000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Don Music",
        management="Don Musik",
        booking_agency=None,
    ),
    "lomepal": KnownArtistData(
        name="Lomepal",
        real_name="Antoine Music",
        genre="RAP",
        spotify_monthly_listeners=4000000,
        youtube_subscribers=1500000,
        instagram_followers=1200000,
        tiktok_followers=400000,
        fee_min=50000,
        fee_max=100000,
        market_tier="established",
        record_label="Grand Musique Management",
        management="GMM",
        booking_agency=None,
    ),
    "vald": KnownArtistData(
        name="Vald",
        real_name="Valentin Le Du",
        genre="RAP",
        spotify_monthly_listeners=5000000,
        youtube_subscribers=2500000,
        instagram_followers=2000000,
        tiktok_followers=600000,
        fee_min=60000,
        fee_max=120000,
        market_tier="star",
        record_label="Échelon Records",
        management="Échelon",
        booking_agency=None,
    ),
    "niska": KnownArtistData(
        name="Niska",
        real_name="Stanislas Musik",
        genre="RAP",
        spotify_monthly_listeners=4000000,
        youtube_subscribers=3000000,
        instagram_followers=3500000,
        tiktok_followers=800000,
        fee_min=50000,
        fee_max=100000,
        market_tier="established",
        record_label="Rec. 118",
        management="Rec. 118",
        booking_agency=None,
    ),
    "sch": KnownArtistData(
        name="SCH",
        real_name="Julien Musik",
        genre="RAP",
        spotify_monthly_listeners=7500000,
        youtube_subscribers=3500000,
        instagram_followers=4000000,
        tiktok_followers=1200000,
        fee_min=80000,
        fee_max=160000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "ziak": KnownArtistData(
        name="Ziak",
        real_name="Zakaria Musik",
        genre="RAP",
        spotify_monthly_listeners=3000000,
        youtube_subscribers=600000,
        instagram_followers=800000,
        tiktok_followers=400000,
        fee_min=30000,
        fee_max=60000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "werenoi": KnownArtistData(
        name="Werenoi",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=4500000,
        youtube_subscribers=900000,
        instagram_followers=1200000,
        tiktok_followers=600000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "dinos": KnownArtistData(
        name="Dinos",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=600000,
        instagram_followers=700000,
        tiktok_followers=200000,
        fee_min=30000,
        fee_max=60000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "rim'k": KnownArtistData(
        name="Rim'K",
        real_name="Abdelkrim Brahmi",
        genre="RAP",
        spotify_monthly_listeners=2000000,
        youtube_subscribers=1500000,
        instagram_followers=1800000,
        tiktok_followers=300000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "kaaris": KnownArtistData(
        name="Kaaris",
        real_name="Okou Armand Gnakouri",
        genre="RAP",
        spotify_monthly_listeners=3000000,
        youtube_subscribers=2000000,
        instagram_followers=3000000,
        tiktok_followers=500000,
        fee_min=50000,
        fee_max=100000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "lacrim": KnownArtistData(
        name="Lacrim",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=2500000,
        instagram_followers=2800000,
        tiktok_followers=400000,
        fee_min=45000,
        fee_max=90000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "rohff": KnownArtistData(
        name="Rohff",
        real_name="Housni Musik",
        genre="RAP",
        spotify_monthly_listeners=1500000,
        youtube_subscribers=1800000,
        instagram_followers=2000000,
        tiktok_followers=200000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "soprano": KnownArtistData(
        name="Soprano",
        real_name="Saïd M'Roumbaba",
        genre="RAP/POP",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=3000000,
        instagram_followers=3500000,
        tiktok_followers=800000,
        fee_min=60000,
        fee_max=120000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "bigflo & oli": KnownArtistData(
        name="Bigflo & Oli",
        real_name="Florian et Olivio Ordonez",
        genre="RAP",
        spotify_monthly_listeners=4500000,
        youtube_subscribers=4000000,
        instagram_followers=4500000,
        tiktok_followers=1000000,
        fee_min=80000,
        fee_max=160000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    
    # ===== ELECTRO / DJ =====
    "dj snake": KnownArtistData(
        name="DJ Snake",
        real_name="William Grigahcine",
        genre="ELECTRO",
        spotify_monthly_listeners=30000000,
        youtube_subscribers=20000000,
        instagram_followers=12000000,
        tiktok_followers=8000000,
        fee_min=300000,
        fee_max=800000,
        market_tier="mega_star",
        record_label="Interscope",
        management=None,
        booking_agency="WME",
    ),
    "david guetta": KnownArtistData(
        name="David Guetta",
        real_name="Pierre David Guetta",
        genre="ELECTRO",
        spotify_monthly_listeners=45000000,
        youtube_subscribers=25000000,
        instagram_followers=15000000,
        tiktok_followers=10000000,
        fee_min=500000,
        fee_max=1500000,
        market_tier="mega_star",
        record_label="Warner Music",
        management=None,
        booking_agency="CAA",
    ),
    "daft punk": KnownArtistData(
        name="Daft Punk",
        real_name="Thomas Bangalter & Guy-Manuel",
        genre="ELECTRO",
        spotify_monthly_listeners=25000000,
        youtube_subscribers=7000000,
        instagram_followers=2000000,
        tiktok_followers=500000,
        fee_min=1000000,
        fee_max=5000000,
        market_tier="mega_star",
        record_label="Columbia",
        management=None,
        booking_agency=None,  # Groupe dissous
    ),
    "martin solveig": KnownArtistData(
        name="Martin Solveig",
        real_name="Martin Musik",
        genre="ELECTRO",
        spotify_monthly_listeners=8000000,
        youtube_subscribers=2000000,
        instagram_followers=1500000,
        tiktok_followers=300000,
        fee_min=80000,
        fee_max=200000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "kungs": KnownArtistData(
        name="Kungs",
        real_name="Valentin Musik",
        genre="ELECTRO",
        spotify_monthly_listeners=12000000,
        youtube_subscribers=1500000,
        instagram_followers=800000,
        tiktok_followers=400000,
        fee_min=60000,
        fee_max=150000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "ofenbach": KnownArtistData(
        name="Ofenbach",
        real_name="Musik",
        genre="ELECTRO",
        spotify_monthly_listeners=10000000,
        youtube_subscribers=1000000,
        instagram_followers=500000,
        tiktok_followers=200000,
        fee_min=50000,
        fee_max=120000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    
    # ===== POP / VARIETE =====
    "stromae": KnownArtistData(
        name="Stromae",
        real_name="Paul Van Haver",
        genre="POP/ELECTRO",
        spotify_monthly_listeners=20000000,
        youtube_subscribers=8000000,
        instagram_followers=4000000,
        tiktok_followers=2000000,
        fee_min=300000,
        fee_max=700000,
        market_tier="mega_star",
        record_label="Mosaert",
        management="Mosaert",
        booking_agency=None,
    ),
    "angele": KnownArtistData(
        name="Angèle",
        real_name="Angèle Van Laeken",
        genre="POP",
        spotify_monthly_listeners=15000000,
        youtube_subscribers=3000000,
        instagram_followers=4000000,
        tiktok_followers=2500000,
        fee_min=150000,
        fee_max=350000,
        market_tier="superstar",
        record_label="Universal",
        management=None,
        booking_agency=None,
    ),
    "indochine": KnownArtistData(
        name="Indochine",
        real_name="Musik",
        genre="ROCK",
        spotify_monthly_listeners=5000000,
        youtube_subscribers=1000000,
        instagram_followers=500000,
        tiktok_followers=100000,
        fee_min=200000,
        fee_max=500000,
        market_tier="superstar",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "gims": KnownArtistData(
        name="Gims",
        real_name="Gandhi Djuna",
        genre="RAP/POP",
        spotify_monthly_listeners=18000000,  # Données réelles Spotify 2024
        youtube_subscribers=10000000,
        instagram_followers=8000000,
        tiktok_followers=3000000,
        fee_min=120000,
        fee_max=300000,
        market_tier="superstar",
        record_label="TF1 Musique / Play Two",
        management="Monstre Marin Corporation",
        booking_agency=None,
    ),
    "louane": KnownArtistData(
        name="Louane",
        real_name="Anne Peichert",
        genre="POP",
        spotify_monthly_listeners=8000000,
        youtube_subscribers=2500000,
        instagram_followers=3000000,
        tiktok_followers=1500000,
        fee_min=60000,
        fee_max=120000,
        market_tier="star",
        record_label="Universal",
        management=None,
        booking_agency=None,
    ),
    "clara luciani": KnownArtistData(
        name="Clara Luciani",
        real_name="Clara Luciani",
        genre="POP",
        spotify_monthly_listeners=6000000,
        youtube_subscribers=500000,
        instagram_followers=700000,
        tiktok_followers=400000,
        fee_min=50000,
        fee_max=100000,
        market_tier="established",
        record_label="Universal",
        management=None,
        booking_agency=None,
    ),
    "vitaa": KnownArtistData(
        name="Vitaa",
        real_name="Charlotte Musik",
        genre="RNB/POP",
        spotify_monthly_listeners=5000000,
        youtube_subscribers=2000000,
        instagram_followers=3500000,
        tiktok_followers=800000,
        fee_min=50000,
        fee_max=100000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "slimane": KnownArtistData(
        name="Slimane",
        real_name="Slimane Nebchi",
        genre="POP",
        spotify_monthly_listeners=4000000,
        youtube_subscribers=1500000,
        instagram_followers=2000000,
        tiktok_followers=1000000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "amir": KnownArtistData(
        name="Amir",
        real_name="Amir Haddad",
        genre="POP",
        spotify_monthly_listeners=5000000,
        youtube_subscribers=1500000,
        instagram_followers=1800000,
        tiktok_followers=600000,
        fee_min=40000,
        fee_max=90000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "patrick bruel": KnownArtistData(
        name="Patrick Bruel",
        real_name="Patrick Benguigui",
        genre="POP/VARIETE",
        spotify_monthly_listeners=3000000,
        youtube_subscribers=500000,
        instagram_followers=400000,
        tiktok_followers=50000,
        fee_min=100000,
        fee_max=250000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "johnny hallyday": KnownArtistData(
        name="Johnny Hallyday",
        real_name="Jean-Philippe Smet",
        genre="ROCK/VARIETE",
        spotify_monthly_listeners=4000000,
        youtube_subscribers=1000000,
        instagram_followers=500000,
        tiktok_followers=100000,
        fee_min=0,  # Décédé
        fee_max=0,
        market_tier="legend",
        record_label="Warner",
        management=None,
        booking_agency=None,
    ),
    
    # ===== RAP FR - DEVELOPING/EMERGING =====
    "koba lad": KnownArtistData(
        name="Koba LaD",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=1500000,
        instagram_followers=2000000,
        tiktok_followers=500000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "rk": KnownArtistData(
        name="RK",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=2000000,
        youtube_subscribers=1200000,
        instagram_followers=1500000,
        tiktok_followers=300000,
        fee_min=25000,
        fee_max=50000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "zola": KnownArtistData(
        name="Zola",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=1500000,
        youtube_subscribers=600000,
        instagram_followers=700000,
        tiktok_followers=200000,
        fee_min=20000,
        fee_max=40000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "la fouine": KnownArtistData(
        name="La Fouine",
        real_name="Laouni Mouhid",
        genre="RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=2500000,
        instagram_followers=2800000,
        tiktok_followers=400000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "alonzo": KnownArtistData(
        name="Alonzo",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=2000000,
        youtube_subscribers=1500000,
        instagram_followers=2000000,
        tiktok_followers=300000,
        fee_min=30000,
        fee_max=60000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "soolking": KnownArtistData(
        name="Soolking",
        real_name="Musik",
        genre="RAP/POP",
        spotify_monthly_listeners=5000000,
        youtube_subscribers=3000000,
        instagram_followers=3500000,
        tiktok_followers=1000000,
        fee_min=50000,
        fee_max=100000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "dadju": KnownArtistData(
        name="Dadju",
        real_name="Dadju Djuna",
        genre="RNB",
        spotify_monthly_listeners=8000000,
        youtube_subscribers=5000000,
        instagram_followers=6000000,
        tiktok_followers=2000000,
        fee_min=80000,
        fee_max=150000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "tayc": KnownArtistData(
        name="Tayc",
        real_name="Musik",
        genre="RNB",
        spotify_monthly_listeners=6000000,
        youtube_subscribers=1500000,
        instagram_followers=2500000,
        tiktok_followers=1500000,
        fee_min=50000,
        fee_max=100000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "fianso": KnownArtistData(
        name="Fianso",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=3000000,
        youtube_subscribers=1800000,
        instagram_followers=2500000,
        tiktok_followers=500000,
        fee_min=35000,
        fee_max=70000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "gradur": KnownArtistData(
        name="Gradur",
        real_name="Musik",
        genre="RAP",
        spotify_monthly_listeners=1500000,
        youtube_subscribers=1200000,
        instagram_followers=1800000,
        tiktok_followers=300000,
        fee_min=25000,
        fee_max=50000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    
    # ===== RAP FR - ARTISTES ÉMERGENTS / EN DÉVELOPPEMENT =====
    "kerchak": KnownArtistData(
        name="Kerchak",
        real_name="Kerchak",
        genre="RAP",
        spotify_monthly_listeners=2800000,
        youtube_subscribers=350000,
        instagram_followers=400000,
        tiktok_followers=150000,
        fee_min=15000,
        fee_max=35000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "rsko": KnownArtistData(
        name="Rsko",
        real_name="Rsko",
        genre="RAP",
        spotify_monthly_listeners=1800000,
        youtube_subscribers=200000,
        instagram_followers=300000,
        tiktok_followers=100000,
        fee_min=10000,
        fee_max=25000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "blaize": KnownArtistData(
        name="Blaize",
        real_name="Blaize",
        genre="RAP",
        spotify_monthly_listeners=800000,
        youtube_subscribers=80000,
        instagram_followers=150000,
        tiktok_followers=50000,
        fee_min=5000,
        fee_max=12000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "nayra": KnownArtistData(
        name="Nayra",
        real_name="Nayra",
        genre="RAP/R&B",
        spotify_monthly_listeners=250000,
        youtube_subscribers=30000,
        instagram_followers=80000,
        tiktok_followers=120000,
        fee_min=2500,
        fee_max=6000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "enigma": KnownArtistData(
        name="Enigma",
        real_name="Enigma",
        genre="RAP",
        spotify_monthly_listeners=600000,
        youtube_subscribers=60000,
        instagram_followers=100000,
        tiktok_followers=80000,
        fee_min=4000,
        fee_max=10000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "nahir": KnownArtistData(
        name="Nahir",
        real_name="Nahir",
        genre="RAP",
        spotify_monthly_listeners=1200000,
        youtube_subscribers=150000,
        instagram_followers=200000,
        tiktok_followers=100000,
        fee_min=8000,
        fee_max=18000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "favé": KnownArtistData(
        name="Favé",
        real_name="Favé",
        genre="RAP",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=300000,
        fee_min=20000,
        fee_max=45000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "fave": KnownArtistData(
        name="Favé",
        real_name="Favé",
        genre="RAP",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=300000,
        fee_min=20000,
        fee_max=45000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "chily": KnownArtistData(
        name="Chily",
        real_name="Chily",
        genre="RAP",
        spotify_monthly_listeners=1500000,
        youtube_subscribers=250000,
        instagram_followers=350000,
        tiktok_followers=150000,
        fee_min=12000,
        fee_max=28000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "menace santana": KnownArtistData(
        name="Menace Santana",
        real_name="Menace Santana",
        genre="RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=350000,
        instagram_followers=400000,
        tiktok_followers=250000,
        fee_min=15000,
        fee_max=35000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "malty 2bl": KnownArtistData(
        name="Malty 2BL",
        real_name="Malty",
        genre="RAP",
        spotify_monthly_listeners=800000,
        youtube_subscribers=100000,
        instagram_followers=150000,
        tiktok_followers=80000,
        fee_min=5000,
        fee_max=12000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "ashe 22": KnownArtistData(
        name="Ashe 22",
        real_name="Ashe 22",
        genre="RAP",
        spotify_monthly_listeners=2000000,
        youtube_subscribers=300000,
        instagram_followers=350000,
        tiktok_followers=200000,
        fee_min=12000,
        fee_max=28000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "jolagreen23": KnownArtistData(
        name="JolaGreen23",
        real_name="JolaGreen",
        genre="RAP",
        spotify_monthly_listeners=1000000,
        youtube_subscribers=150000,
        instagram_followers=200000,
        tiktok_followers=100000,
        fee_min=6000,
        fee_max=15000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "le juiice": KnownArtistData(
        name="Le Juiice",
        real_name="Le Juiice",
        genre="RAP",
        spotify_monthly_listeners=700000,
        youtube_subscribers=120000,
        instagram_followers=180000,
        tiktok_followers=150000,
        fee_min=5000,
        fee_max=12000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "luidji": KnownArtistData(
        name="Luidji",
        real_name="Luidji",
        genre="RAP/RNB",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=200000,
        instagram_followers=300000,
        tiktok_followers=100000,
        fee_min=15000,
        fee_max=35000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "josman": KnownArtistData(
        name="Josman",
        real_name="Josman",
        genre="RAP",
        spotify_monthly_listeners=4000000,
        youtube_subscribers=600000,
        instagram_followers=700000,
        tiktok_followers=300000,
        fee_min=30000,
        fee_max=60000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "youv dee": KnownArtistData(
        name="Youv Dee",
        real_name="Youv Dee",
        genre="RAP",
        spotify_monthly_listeners=1500000,
        youtube_subscribers=200000,
        instagram_followers=250000,
        tiktok_followers=100000,
        fee_min=10000,
        fee_max=22000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "so la lune": KnownArtistData(
        name="So La Lune",
        real_name="So La Lune",
        genre="RAP",
        spotify_monthly_listeners=2200000,
        youtube_subscribers=250000,
        instagram_followers=350000,
        tiktok_followers=200000,
        fee_min=12000,
        fee_max=28000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "tsew the kid": KnownArtistData(
        name="Tsew The Kid",
        real_name="Tsew",
        genre="RAP",
        spotify_monthly_listeners=1800000,
        youtube_subscribers=250000,
        instagram_followers=300000,
        tiktok_followers=150000,
        fee_min=10000,
        fee_max=22000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "guy2bezbar": KnownArtistData(
        name="Guy2Bezbar",
        real_name="Guy2Bezbar",
        genre="RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=250000,
        fee_min=15000,
        fee_max=35000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "uzi": KnownArtistData(
        name="Uzi",
        real_name="Uzi",
        genre="RAP",
        spotify_monthly_listeners=3000000,
        youtube_subscribers=450000,
        instagram_followers=550000,
        tiktok_followers=300000,
        fee_min=18000,
        fee_max=40000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "bosh": KnownArtistData(
        name="Bosh",
        real_name="Bosh",
        genre="RAP",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=500000,
        instagram_followers=600000,
        tiktok_followers=350000,
        fee_min=25000,
        fee_max=50000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "mali": KnownArtistData(
        name="Mali",
        real_name="Mali",
        genre="RAP",
        spotify_monthly_listeners=900000,
        youtube_subscribers=100000,
        instagram_followers=150000,
        tiktok_followers=80000,
        fee_min=5000,
        fee_max=12000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "yorssy": KnownArtistData(
        name="Yorssy",
        real_name="Yorssy",
        genre="RAP",
        spotify_monthly_listeners=500000,
        youtube_subscribers=50000,
        instagram_followers=80000,
        tiktok_followers=40000,
        fee_min=3000,
        fee_max=8000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "yamê": KnownArtistData(
        name="Yamê",
        real_name="Yamê",
        genre="POP/RNB",
        spotify_monthly_listeners=4500000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=600000,
        fee_min=25000,
        fee_max=55000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "yame": KnownArtistData(
        name="Yamê",
        real_name="Yamê",
        genre="POP/RNB",
        spotify_monthly_listeners=4500000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=600000,
        fee_min=25000,
        fee_max=55000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    
    # ===== DJ / PRODUCTEURS FRANÇAIS =====
    "dj bens": KnownArtistData(
        name="DJ Bens",
        real_name="Benjamin",
        genre="DJ/HIP-HOP",
        spotify_monthly_listeners=150000,
        youtube_subscribers=50000,
        instagram_followers=100000,
        tiktok_followers=30000,
        fee_min=3000,
        fee_max=8000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "dj snake": KnownArtistData(
        name="DJ Snake",
        real_name="William Grigahcine",
        genre="ELECTRO",
        spotify_monthly_listeners=30000000,
        youtube_subscribers=20000000,
        instagram_followers=12000000,
        tiktok_followers=8000000,
        fee_min=300000,
        fee_max=800000,
        market_tier="mega_star",
        record_label="Interscope",
        management=None,
        booking_agency="WME",
    ),
    "dj kore": KnownArtistData(
        name="DJ Kore",
        real_name="DJ Kore",
        genre="DJ/HIP-HOP",
        spotify_monthly_listeners=80000,
        youtube_subscribers=30000,
        instagram_followers=50000,
        tiktok_followers=10000,
        fee_min=2000,
        fee_max=5000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "dj mehdi": KnownArtistData(
        name="DJ Mehdi",
        real_name="Mehdi Faveris-Essadi",
        genre="ELECTRO/HIP-HOP",
        spotify_monthly_listeners=500000,
        youtube_subscribers=50000,
        instagram_followers=0,
        tiktok_followers=0,
        fee_min=0,
        fee_max=0,
        market_tier="legend",
        record_label="Ed Banger",
        management=None,
        booking_agency=None,
    ),
    "dj pone": KnownArtistData(
        name="DJ Pone",
        real_name="DJ Pone",
        genre="DJ/HIP-HOP",
        spotify_monthly_listeners=100000,
        youtube_subscribers=20000,
        instagram_followers=40000,
        tiktok_followers=5000,
        fee_min=2500,
        fee_max=6000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "dj weedim": KnownArtistData(
        name="DJ Weedim",
        real_name="DJ Weedim",
        genre="DJ/HIP-HOP",
        spotify_monthly_listeners=200000,
        youtube_subscribers=40000,
        instagram_followers=60000,
        tiktok_followers=20000,
        fee_min=3000,
        fee_max=7000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "dj cream": KnownArtistData(
        name="DJ Cream",
        real_name="DJ Cream",
        genre="DJ/HIP-HOP",
        spotify_monthly_listeners=50000,
        youtube_subscribers=15000,
        instagram_followers=30000,
        tiktok_followers=8000,
        fee_min=1500,
        fee_max=4000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "dj quick": KnownArtistData(
        name="DJ Quick",
        real_name="DJ Quick",
        genre="DJ/HIP-HOP",
        spotify_monthly_listeners=100000,
        youtube_subscribers=25000,
        instagram_followers=45000,
        tiktok_followers=10000,
        fee_min=2000,
        fee_max=5000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "dj bellek": KnownArtistData(
        name="DJ Bellek",
        real_name="DJ Bellek",
        genre="DJ/HIP-HOP",
        spotify_monthly_listeners=80000,
        youtube_subscribers=20000,
        instagram_followers=35000,
        tiktok_followers=15000,
        fee_min=1500,
        fee_max=4000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    
    # ===== CHANTEUSES FRANÇAISES ÉMERGENTES =====
    "wejdene": KnownArtistData(
        name="Wejdene",
        real_name="Wejdene",
        genre="POP/RNB",
        spotify_monthly_listeners=3000000,
        youtube_subscribers=1500000,
        instagram_followers=2500000,
        tiktok_followers=2000000,
        fee_min=25000,
        fee_max=55000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "eva": KnownArtistData(
        name="Eva",
        real_name="Eva Queen",
        genre="POP/RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=1200000,
        instagram_followers=2000000,
        tiktok_followers=1500000,
        fee_min=20000,
        fee_max=45000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "eva queen": KnownArtistData(
        name="Eva Queen",
        real_name="Eva Queen",
        genre="POP/RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=1200000,
        instagram_followers=2000000,
        tiktok_followers=1500000,
        fee_min=20000,
        fee_max=45000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "laeti": KnownArtistData(
        name="Laeti",
        real_name="Laeti",
        genre="POP",
        spotify_monthly_listeners=800000,
        youtube_subscribers=100000,
        instagram_followers=150000,
        tiktok_followers=80000,
        fee_min=5000,
        fee_max=12000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "emma peters": KnownArtistData(
        name="Emma Peters",
        real_name="Emma Peters",
        genre="POP",
        spotify_monthly_listeners=1500000,
        youtube_subscribers=150000,
        instagram_followers=200000,
        tiktok_followers=100000,
        fee_min=8000,
        fee_max=18000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "lolo zouai": KnownArtistData(
        name="Lolo Zouai",
        real_name="Lolo Zouai",
        genre="POP/RNB",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=300000,
        instagram_followers=500000,
        tiktok_followers=400000,
        fee_min=20000,
        fee_max=45000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "joanna": KnownArtistData(
        name="Joanna",
        real_name="Joanna",
        genre="POP/RNB",
        spotify_monthly_listeners=600000,
        youtube_subscribers=80000,
        instagram_followers=120000,
        tiktok_followers=60000,
        fee_min=4000,
        fee_max=10000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "theodora": KnownArtistData(
        name="Theodora",
        real_name="Theodora",
        genre="POP",
        spotify_monthly_listeners=400000,
        youtube_subscribers=50000,
        instagram_followers=80000,
        tiktok_followers=40000,
        fee_min=3000,
        fee_max=8000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "silly boy blue": KnownArtistData(
        name="Silly Boy Blue",
        real_name="Silly Boy Blue",
        genre="POP",
        spotify_monthly_listeners=300000,
        youtube_subscribers=30000,
        instagram_followers=50000,
        tiktok_followers=20000,
        fee_min=2500,
        fee_max=6000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "pomme": KnownArtistData(
        name="Pomme",
        real_name="Claire Pommet",
        genre="POP/FOLK",
        spotify_monthly_listeners=3500000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=200000,
        fee_min=25000,
        fee_max=55000,
        market_tier="established",
        record_label="Universal",
        management=None,
        booking_agency=None,
    ),
    "hoshi": KnownArtistData(
        name="Hoshi",
        real_name="Mathilde Music",
        genre="POP",
        spotify_monthly_listeners=4000000,
        youtube_subscribers=500000,
        instagram_followers=600000,
        tiktok_followers=400000,
        fee_min=30000,
        fee_max=60000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "yseult": KnownArtistData(
        name="Yseult",
        real_name="Yseult",
        genre="POP/RNB",
        spotify_monthly_listeners=2000000,
        youtube_subscribers=300000,
        instagram_followers=400000,
        tiktok_followers=250000,
        fee_min=18000,
        fee_max=40000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "zaho de sagazan": KnownArtistData(
        name="Zaho de Sagazan",
        real_name="Zaho de Sagazan",
        genre="POP",
        spotify_monthly_listeners=5000000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=300000,
        fee_min=35000,
        fee_max=70000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "juliette armanet": KnownArtistData(
        name="Juliette Armanet",
        real_name="Juliette Armanet",
        genre="POP",
        spotify_monthly_listeners=3000000,
        youtube_subscribers=200000,
        instagram_followers=300000,
        tiktok_followers=100000,
        fee_min=25000,
        fee_max=55000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    
    # ===== RAPPEURS ÉMERGENTS 2024-2025 =====
    "khan music": KnownArtistData(
        name="Khan Music",
        real_name="Khan",
        genre="RAP",
        spotify_monthly_listeners=400000,
        youtube_subscribers=40000,
        instagram_followers=60000,
        tiktok_followers=30000,
        fee_min=2500,
        fee_max=6000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "yungkha": KnownArtistData(
        name="YungKha",
        real_name="YungKha",
        genre="RAP",
        spotify_monthly_listeners=300000,
        youtube_subscribers=30000,
        instagram_followers=50000,
        tiktok_followers=40000,
        fee_min=2000,
        fee_max=5000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "lala &ce": KnownArtistData(
        name="Lala &ce",
        real_name="Lala",
        genre="RAP",
        spotify_monthly_listeners=1500000,
        youtube_subscribers=150000,
        instagram_followers=250000,
        tiktok_followers=150000,
        fee_min=10000,
        fee_max=22000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "zinée": KnownArtistData(
        name="Zinée",
        real_name="Zinée",
        genre="RAP",
        spotify_monthly_listeners=700000,
        youtube_subscribers=80000,
        instagram_followers=120000,
        tiktok_followers=80000,
        fee_min=5000,
        fee_max=12000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "zinee": KnownArtistData(
        name="Zinée",
        real_name="Zinée",
        genre="RAP",
        spotify_monthly_listeners=700000,
        youtube_subscribers=80000,
        instagram_followers=120000,
        tiktok_followers=80000,
        fee_min=5000,
        fee_max=12000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "leys": KnownArtistData(
        name="Leys",
        real_name="Leys",
        genre="RAP",
        spotify_monthly_listeners=1800000,
        youtube_subscribers=200000,
        instagram_followers=300000,
        tiktok_followers=150000,
        fee_min=10000,
        fee_max=25000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "landy": KnownArtistData(
        name="Landy",
        real_name="Landy",
        genre="RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=400000,
        instagram_followers=500000,
        tiktok_followers=250000,
        fee_min=18000,
        fee_max=40000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "da uzi": KnownArtistData(
        name="DA Uzi",
        real_name="DA Uzi",
        genre="RAP",
        spotify_monthly_listeners=2000000,
        youtube_subscribers=350000,
        instagram_followers=450000,
        tiktok_followers=200000,
        fee_min=15000,
        fee_max=35000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "maes": KnownArtistData(
        name="Maes",
        real_name="Maes",
        genre="RAP",
        spotify_monthly_listeners=5000000,
        youtube_subscribers=2000000,
        instagram_followers=3000000,
        tiktok_followers=800000,
        fee_min=50000,
        fee_max=100000,
        market_tier="star",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "rim k": KnownArtistData(
        name="Rim'K",
        real_name="Abdelkrim Brahmi",
        genre="RAP",
        spotify_monthly_listeners=2000000,
        youtube_subscribers=1500000,
        instagram_followers=1800000,
        tiktok_followers=300000,
        fee_min=40000,
        fee_max=80000,
        market_tier="established",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "gambi": KnownArtistData(
        name="Gambi",
        real_name="Gambi",
        genre="RAP",
        spotify_monthly_listeners=2800000,
        youtube_subscribers=500000,
        instagram_followers=700000,
        tiktok_followers=500000,
        fee_min=20000,
        fee_max=45000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "green montana": KnownArtistData(
        name="Green Montana",
        real_name="Green Montana",
        genre="RAP",
        spotify_monthly_listeners=1200000,
        youtube_subscribers=150000,
        instagram_followers=200000,
        tiktok_followers=100000,
        fee_min=8000,
        fee_max=18000,
        market_tier="developing",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "benjamin epps": KnownArtistData(
        name="Benjamin Epps",
        real_name="Benjamin Music",
        genre="RAP",
        spotify_monthly_listeners=2500000,
        youtube_subscribers=300000,
        instagram_followers=350000,
        tiktok_followers=150000,
        fee_min=15000,
        fee_max=35000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "bianca costa": KnownArtistData(
        name="Bianca Costa",
        real_name="Bianca Costa",
        genre="RAP",
        spotify_monthly_listeners=900000,
        youtube_subscribers=100000,
        instagram_followers=150000,
        tiktok_followers=120000,
        fee_min=6000,
        fee_max=14000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "jungeli": KnownArtistData(
        name="Jungeli",
        real_name="Jungeli",
        genre="RAP",
        spotify_monthly_listeners=500000,
        youtube_subscribers=60000,
        instagram_followers=100000,
        tiktok_followers=60000,
        fee_min=3500,
        fee_max=8000,
        market_tier="emerging",
        record_label=None,
        management=None,
        booking_agency=None,
    ),
    "bolémvn": KnownArtistData(
        name="Bolémvn",
        real_name="Bolémvn",
        genre="RAP",
        spotify_monthly_listeners=1800000,
        youtube_subscribers=200000,
        instagram_followers=300000,
        tiktok_followers=180000,
        fee_min=12000,
        fee_max=28000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
    "bolemvn": KnownArtistData(
        name="Bolémvn",
        real_name="Bolémvn",
        genre="RAP",
        spotify_monthly_listeners=1800000,
        youtube_subscribers=200000,
        instagram_followers=300000,
        tiktok_followers=180000,
        fee_min=12000,
        fee_max=28000,
        market_tier="developing",
        record_label="Musik",
        management=None,
        booking_agency=None,
    ),
}


def get_known_artist(name: str) -> Optional[KnownArtistData]:
    """
    Recherche un artiste dans la base de données.
    Effectue une recherche insensible à la casse et aux accents.
    """
    # Normaliser le nom
    normalized = name.lower().strip()
    
    # Recherche directe
    if normalized in KNOWN_ARTISTS_DB:
        return KNOWN_ARTISTS_DB[normalized]
    
    # Recherche avec variantes
    # Enlever les accents courants
    normalized_no_accent = (
        normalized
        .replace('é', 'e')
        .replace('è', 'e')
        .replace('ê', 'e')
        .replace('ë', 'e')
        .replace('à', 'a')
        .replace('â', 'a')
        .replace('ù', 'u')
        .replace('û', 'u')
        .replace('ô', 'o')
        .replace('î', 'i')
        .replace('ï', 'i')
        .replace('ç', 'c')
    )
    
    for key, data in KNOWN_ARTISTS_DB.items():
        key_normalized = (
            key
            .replace('é', 'e')
            .replace('è', 'e')
            .replace('ê', 'e')
            .replace('ë', 'e')
            .replace('à', 'a')
            .replace('â', 'a')
            .replace('ù', 'u')
            .replace('û', 'u')
            .replace('ô', 'o')
            .replace('î', 'i')
            .replace('ï', 'i')
            .replace('ç', 'c')
        )
        
        # Match exact ou partiel
        if normalized_no_accent == key_normalized:
            return data
        
        # Match sur le nom complet de l'artiste
        if data.name.lower() == normalized:
            return data
    
    return None


def search_similar_artists(name: str, limit: int = 5) -> list:
    """
    Recherche des artistes similaires au nom donné.
    Utile pour les suggestions.
    """
    normalized = name.lower().strip()
    results = []
    
    for key, data in KNOWN_ARTISTS_DB.items():
        # Score de similarité simple
        if normalized in key or key in normalized:
            results.append(data)
        elif normalized in data.name.lower() or data.name.lower() in normalized:
            results.append(data)
    
    return results[:limit]


def get_emerging_artists(limit: int = 10) -> list:
    """
    Retourne les artistes émergents avec fort potentiel.
    Critères:
    - market_tier = "emerging" ou "developing"
    - Prix abordables (< 30000€)
    - Présence Spotify significative (> 200K auditeurs)
    
    Résultats VRAIMENT ALÉATOIRES pour découvrir de nouveaux artistes !
    """
    emerging = []
    
    for key, data in KNOWN_ARTISTS_DB.items():
        if data.market_tier in ["emerging", "developing"]:
            if data.fee_max <= 30000 and data.spotify_monthly_listeners >= 200000:
                # Calculer un score de potentiel
                # = auditeurs par euro dépensé (plus c'est haut, meilleur est le deal)
                potential_score = data.spotify_monthly_listeners / max(data.fee_max, 1)
                emerging.append({
                    "artist": data,
                    "potential_score": potential_score,
                })
    
    # MÉLANGER ALÉATOIREMENT pour découvrir de nouveaux artistes
    random.shuffle(emerging)
    
    # Enlever les doublons (même artiste avec accents différents)
    seen_names = set()
    unique_results = []
    for item in emerging:
        name_lower = item["artist"].name.lower()
        if name_lower not in seen_names:
            seen_names.add(name_lower)
            unique_results.append(item["artist"])
    
    return unique_results[:limit]


def get_rising_artists(limit: int = 10) -> list:
    """
    Retourne les artistes en forte progression.
    Focus sur les artistes "developing" qui sont proches de devenir "established"
    
    Résultats VRAIMENT ALÉATOIRES pour découvrir de nouveaux artistes !
    """
    rising = []
    
    for key, data in KNOWN_ARTISTS_DB.items():
        if data.market_tier == "developing":
            # Artistes avec bonne présence mais prix encore raisonnables
            if data.spotify_monthly_listeners >= 1000000 and data.fee_max <= 50000:
                rising.append(data)
    
    # MÉLANGER ALÉATOIREMENT pour découvrir de nouveaux artistes
    random.shuffle(rising)
    
    # Enlever les doublons
    seen_names = set()
    unique_results = []
    for artist in rising:
        name_lower = artist.name.lower()
        if name_lower not in seen_names:
            seen_names.add(name_lower)
            unique_results.append(artist)
    
    return unique_results[:limit]


def get_budget_friendly_artists(max_budget: int = 15000, limit: int = 10) -> list:
    """
    Retourne les artistes avec le meilleur rapport qualité/prix
    pour un budget donné.
    
    Résultats VRAIMENT ALÉATOIRES pour découvrir de nouveaux artistes !
    """
    affordable = []
    
    for key, data in KNOWN_ARTISTS_DB.items():
        # Exclure les artistes avec fee_min = 0 (décédés ou indisponibles)
        if data.fee_min > 0 and data.fee_min <= max_budget and data.spotify_monthly_listeners >= 100000:
            # Calculer le rapport qualité/prix
            value_score = data.spotify_monthly_listeners / max(data.fee_min, 1)
            affordable.append({
                "artist": data,
                "value_score": value_score,
            })
    
    # MÉLANGER ALÉATOIREMENT pour découvrir de nouveaux artistes
    random.shuffle(affordable)
    
    # Enlever les doublons
    seen_names = set()
    unique_results = []
    for item in affordable:
        name_lower = item["artist"].name.lower()
        if name_lower not in seen_names:
            seen_names.add(name_lower)
            unique_results.append(item["artist"])
    
    return unique_results[:limit]


def get_genre_artists(genre: str, limit: int = 10) -> list:
    """
    Retourne les artistes d'un genre spécifique.
    """
    genre_lower = genre.lower()
    results = []
    
    for key, data in KNOWN_ARTISTS_DB.items():
        if genre_lower in data.genre.lower():
            results.append(data)
    
    # Trier par popularité
    results.sort(key=lambda x: x.spotify_monthly_listeners, reverse=True)
    
    # Enlever les doublons
    seen_names = set()
    unique_results = []
    for artist in results:
        name_lower = artist.name.lower()
        if name_lower not in seen_names:
            seen_names.add(name_lower)
            unique_results.append(artist)
    
    return unique_results[:limit]
